/* eslint-disable @next/next/no-img-element */
import { type CSSProperties } from "react";

interface BlogTemplateProps {
  title: string;
  subtitle?: string;
  logo?: string;
  theme?: "light" | "dark";
  bgColor?: string;
  textColor?: string;
  author?: string;
  date?: string;
  readingTime?: string;
  width: number;
  height: number;
  showWatermark?: boolean;
}

export function BlogTemplate({
  title,
  subtitle,
  logo,
  theme = "light",
  bgColor,
  textColor,
  author,
  date,
  readingTime,
  showWatermark,
}: BlogTemplateProps) {
  const isDark = theme === "dark";
  const bg = bgColor || (isDark ? "#1a1a2e" : "#fafafa");
  const text = textColor || (isDark ? "#e2e8f0" : "#1e293b");
  const mutedText = isDark ? "#94a3b8" : "#64748b";
  const borderColor = isDark ? "#334155" : "#e2e8f0";
  const accent = isDark ? "#a78bfa" : "#7c3aed";

  const containerStyle: CSSProperties = {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: bg,
    padding: "60px 80px",
    fontFamily: "system-ui, sans-serif",
  };

  return (
    <div style={containerStyle}>
      {/* Top bar */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          {logo && (
            <img
              src={logo}
              alt=""
              width={40}
              height={40}
              style={{ borderRadius: 8 }}
            />
          )}
          <span style={{ fontSize: 14, color: mutedText, textTransform: "uppercase", letterSpacing: 2 }}>
            Blog
          </span>
        </div>
        {readingTime && (
          <span style={{ fontSize: 16, color: mutedText }}>
            {readingTime} min read
          </span>
        )}
      </div>

      {/* Title area */}
      <div style={{ display: "flex", flexDirection: "column", gap: 16, flex: 1, justifyContent: "center" }}>
        <h1
          style={{
            fontSize: title.length > 50 ? 40 : 52,
            fontWeight: 800,
            color: text,
            lineHeight: 1.15,
            margin: 0,
          }}
        >
          {title}
        </h1>
        {subtitle && (
          <p style={{ fontSize: 22, color: mutedText, margin: 0, lineHeight: 1.4 }}>
            {subtitle}
          </p>
        )}
      </div>

      {/* Bottom bar */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderTop: `2px solid ${borderColor}`,
          paddingTop: 24,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          {author && (
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <div
                style={{
                  width: 44,
                  height: 44,
                  borderRadius: 22,
                  backgroundColor: accent,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "#fff",
                  fontSize: 18,
                  fontWeight: 700,
                }}
              >
                {author.charAt(0).toUpperCase()}
              </div>
              <span style={{ fontSize: 18, color: text, fontWeight: 600 }}>{author}</span>
            </div>
          )}
        </div>
        {date && (
          <span style={{ fontSize: 16, color: mutedText }}>{date}</span>
        )}
      </div>

      {showWatermark && (
        <div
          style={{
            position: "absolute",
            bottom: 20,
            right: 30,
            fontSize: 14,
            color: isDark ? "#475569" : "#cbd5e1",
          }}
        >
          Generated by ogimage-api
        </div>
      )}
    </div>
  );
}
