/* eslint-disable @next/next/no-img-element */
import { type CSSProperties } from "react";

interface DefaultTemplateProps {
  title: string;
  subtitle?: string;
  logo?: string;
  theme?: "light" | "dark";
  bgColor?: string;
  textColor?: string;
  width: number;
  height: number;
  showWatermark?: boolean;
}

export function DefaultTemplate({
  title,
  subtitle,
  logo,
  theme = "light",
  bgColor,
  textColor,
  width,
  showWatermark,
}: DefaultTemplateProps) {
  const isDark = theme === "dark";
  const bg = bgColor || (isDark ? "#0f172a" : "#ffffff");
  const text = textColor || (isDark ? "#f1f5f9" : "#0f172a");
  const subtitleColor = isDark ? "#94a3b8" : "#64748b";
  const accent = isDark ? "#3b82f6" : "#2563eb";

  const containerStyle: CSSProperties = {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    width: "100%",
    height: "100%",
    backgroundColor: bg,
    padding: "60px 80px",
    fontFamily: "system-ui, sans-serif",
  };

  return (
    <div style={containerStyle}>
      <div style={{ display: "flex", alignItems: "center", marginBottom: 40 }}>
        {logo && (
          <img
            src={logo}
            alt=""
            width={60}
            height={60}
            style={{ borderRadius: 12, marginRight: 20 }}
          />
        )}
        <div
          style={{
            width: 60,
            height: 6,
            backgroundColor: accent,
            borderRadius: 3,
          }}
        />
      </div>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: 16,
          maxWidth: width - 160,
        }}
      >
        <h1
          style={{
            fontSize: title.length > 60 ? 42 : 56,
            fontWeight: 700,
            color: text,
            lineHeight: 1.1,
            margin: 0,
          }}
        >
          {title}
        </h1>

        {subtitle && (
          <p
            style={{
              fontSize: 24,
              color: subtitleColor,
              lineHeight: 1.4,
              margin: 0,
            }}
          >
            {subtitle}
          </p>
        )}
      </div>

      {showWatermark && (
        <div
          style={{
            position: "absolute",
            bottom: 20,
            right: 30,
            fontSize: 14,
            color: isDark ? "#475569" : "#cbd5e1",
          }}
        >
          Generated by ogimage-api
        </div>
      )}
    </div>
  );
}
