import { type CSSProperties } from "react";

interface MinimalTemplateProps {
  title: string;
  subtitle?: string;
  theme?: "light" | "dark";
  bgColor?: string;
  textColor?: string;
  width: number;
  height: number;
  showWatermark?: boolean;
}

export function MinimalTemplate({
  title,
  subtitle,
  theme = "light",
  bgColor,
  textColor,
  showWatermark,
}: MinimalTemplateProps) {
  const isDark = theme === "dark";
  const bg = bgColor || (isDark ? "#000000" : "#f8fafc");
  const text = textColor || (isDark ? "#ffffff" : "#0f172a");

  const containerStyle: CSSProperties = {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
    backgroundColor: bg,
    padding: "60px 100px",
    fontFamily: "system-ui, sans-serif",
    textAlign: "center",
  };

  return (
    <div style={containerStyle}>
      <h1
        style={{
          fontSize: title.length > 40 ? 52 : 72,
          fontWeight: 900,
          color: text,
          lineHeight: 1.05,
          margin: 0,
          letterSpacing: "-0.02em",
        }}
      >
        {title}
      </h1>

      {subtitle && (
        <p
          style={{
            fontSize: 28,
            color: isDark ? "#a1a1aa" : "#71717a",
            marginTop: 24,
            lineHeight: 1.3,
          }}
        >
          {subtitle}
        </p>
      )}

      {showWatermark && (
        <div
          style={{
            position: "absolute",
            bottom: 20,
            right: 30,
            fontSize: 14,
            color: isDark ? "#3f3f46" : "#d4d4d8",
          }}
        >
          Generated by ogimage-api
        </div>
      )}
    </div>
  );
}
