/* eslint-disable @next/next/no-img-element */
import { type CSSProperties } from "react";

interface ProductTemplateProps {
  title: string;
  subtitle?: string;
  logo?: string;
  theme?: "light" | "dark";
  bgColor?: string;
  textColor?: string;
  price?: string;
  cta?: string;
  productImage?: string;
  width: number;
  height: number;
  showWatermark?: boolean;
}

export function ProductTemplate({
  title,
  subtitle,
  logo,
  theme = "light",
  bgColor,
  textColor,
  price,
  cta,
  productImage,
  showWatermark,
}: ProductTemplateProps) {
  const isDark = theme === "dark";
  const bg = bgColor || (isDark ? "#111827" : "#ffffff");
  const text = textColor || (isDark ? "#f9fafb" : "#111827");
  const mutedText = isDark ? "#9ca3af" : "#6b7280";
  const accent = "#10b981";
  const ctaBg = isDark ? "#10b981" : "#059669";

  const containerStyle: CSSProperties = {
    display: "flex",
    width: "100%",
    height: "100%",
    backgroundColor: bg,
    fontFamily: "system-ui, sans-serif",
  };

  return (
    <div style={containerStyle}>
      {/* Left side — product info */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "60px 60px",
          flex: 1,
          gap: 20,
        }}
      >
        {logo && (
          <img
            src={logo}
            alt=""
            width={48}
            height={48}
            style={{ borderRadius: 10 }}
          />
        )}

        <h1
          style={{
            fontSize: title.length > 40 ? 36 : 46,
            fontWeight: 800,
            color: text,
            lineHeight: 1.1,
            margin: 0,
          }}
        >
          {title}
        </h1>

        {subtitle && (
          <p style={{ fontSize: 20, color: mutedText, margin: 0, lineHeight: 1.4 }}>
            {subtitle}
          </p>
        )}

        <div style={{ display: "flex", alignItems: "center", gap: 20, marginTop: 8 }}>
          {price && (
            <span style={{ fontSize: 36, fontWeight: 800, color: accent }}>
              {price}
            </span>
          )}
          {cta && (
            <div
              style={{
                display: "flex",
                backgroundColor: ctaBg,
                color: "#ffffff",
                padding: "12px 28px",
                borderRadius: 10,
                fontSize: 18,
                fontWeight: 700,
              }}
            >
              {cta}
            </div>
          )}
        </div>
      </div>

      {/* Right side — product image */}
      {productImage && (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            width: "45%",
            padding: 40,
          }}
        >
          <img
            src={productImage}
            alt=""
            width={400}
            height={400}
            style={{ objectFit: "contain", borderRadius: 16 }}
          />
        </div>
      )}

      {showWatermark && (
        <div
          style={{
            position: "absolute",
            bottom: 20,
            right: 30,
            fontSize: 14,
            color: isDark ? "#475569" : "#cbd5e1",
          }}
        >
          Generated by ogimage-api
        </div>
      )}
    </div>
  );
}
